name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  random-contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Boiling Directory
        run: mkdir -p boiling

      - name: Generate Random Job Count
        id: random-count
        run: echo "JOB_COUNT=$((RANDOM % 10 + 1))" >> $GITHUB_ENV

      - name: Execute and Commit Random Jobs
        run: |
          for ((i=1; i<=$JOB_COUNT; i++)); do
            # Generate file or perform action based on the random task
            case $((i % 10 + 1)) in
              1)
                echo "Random Quote: '$(curl -s https://api.quotable.io/random | jq -r '.content')" >> boiling/README.md
                ;;
              2)
                curl -s https://artii.herokuapp.com/make?text=GitHub > boiling/ascii_art.txt
                ;;
              3)
                echo "Log entry $i: $(date)" >> boiling/log.txt
                ;;
              4)
                progress=$((RANDOM % 100))
                echo "Today's progress ($i): $progress%" >> boiling/progress.txt
                ;;
              5)
                filename="boiling/file.txt"
                echo "Random Content for $filename" > $filename
                ;;
              6)
                joke=$(curl -s https://official-joke-api.appspot.com/random_joke | jq -r '.setup + " - " + .punchline')
                echo "Random Joke $i: $joke" >> boiling/jokes.txt
                ;;
              7)
                echo "ASCII Art $i" >> boiling/ascii_art_summary.txt
                curl -s https://artii.herokuapp.com/make?text=Commit$i >> boiling/ascii_art_summary.txt
                ;;
              8)
                echo "Random fact $i: $(curl -s https://uselessfacts.jsph.pl/random.json?language=en | jq -r '.text')" >> boiling/facts.txt
                ;;
              9)
                echo "Simulated task $i at $(date)" > boiling/task.txt
                ;;
              10)
                echo "Placeholder file $i created on $(date)" > boiling/placeholder.txt
                ;;
            esac
            
            # Commit changes after each task
            git config user.name "Aditya Kale"
            git config user.email "adityakale732@gmail.com"
            git add boiling/*
            git commit -m "Job $i completed on $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          done
