name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * 5' #
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  random-contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Boiling Directory
        run: mkdir -p boiling

      - name: Generate Random Job Count
        id: random-count
        run: echo "JOB_COUNT=$((RANDOM % 10 + 1))" >> $GITHUB_ENV

      - name: Execute and Commit Random Jobs
        run: |
          for ((i=1; i<=$JOB_COUNT; i++)); do
            current_date=$(date +'%Y-%m-%d %H:%M:%S')
            case $((i % 10 + 1)) in
              1)
                echo "$current_date - Random Quote: '$(curl -s https://api.quotable.io/random | jq -r '.content')" >> boiling/README.md
                ;;
              2)
                echo "$current_date - ASCII Art:" > boiling/ascii_art.txt
                curl -s https://artii.herokuapp.com/make?text=GitHub >> boiling/ascii_art.txt
                ;;
              3)
                echo "$current_date - Log entry $i" >> boiling/log.txt
                ;;
              4)
                progress=$((RANDOM % 100))
                echo "$current_date - Today's progress ($i): $progress%" >> boiling/progress.txt
                ;;
              5)
                filename="boiling/file.txt"
                echo "$current_date - Random Content for $filename" > $filename
                ;;
              6)
                joke=$(curl -s https://official-joke-api.appspot.com/random_joke | jq -r '.setup + " - " + .punchline')
                echo "$current_date - Random Joke $i: $joke" >> boiling/jokes.txt
                ;;
              7)
                echo "$current_date - ASCII Art $i" >> boiling/ascii_art_summary.txt
                curl -s https://artii.herokuapp.com/make?text=Commit$i >> boiling/ascii_art_summary.txt
                ;;
              8)
                echo "$current_date - Random fact $i: $(curl -s https://uselessfacts.jsph.pl/random.json?language=en | jq -r '.text')" >> boiling/facts.txt
                ;;
              9)
                echo "$current_date - Simulated task $i" > boiling/task.txt
                ;;
              10)
                echo "$current_date - Placeholder file $i created" > boiling/placeholder.txt
                ;;
            esac
          
            # Commit changes if there are any
            git config user.name "Aditya Kale"
            git config user.email "adityakale732@gmail.com"
            git add boiling/*
            if ! git diff --cached --quiet; then
              git commit -m "Job $i completed on $current_date"
              git push
            else
              echo "No changes to commit for Job $JOB_COUNT."
            fi
          done

